import { useCallback, useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { createAdministrator, deleteAdminReview, fetchAdminOrder, fetchAdminOrders, fetchAdminProducts, fetchAdminReviews, fetchAdmins, fetchAdminUsers, fetchDashboard, fetchShippingSettings, fetchSiteSettings, updateAdminReview, updateAdministrator, updateShippingSettings, updateSiteSettings } from '../../services/adminApi.js';

const money=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0});
const date=new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'});
const title=(eyebrow,heading,copy,action)=> <header className="na-page-head"><div><p>{eyebrow}</p><h1>{heading}</h1><span>{copy}</span></div>{action}</header>;
const Notice=({error,notice})=>error?<div className="na-message is-error">{error}</div>:notice?<div className="na-message">✓ {notice}</div>:null;
const Load=()=> <div className="na-module-loading"><i/><i/><i/></div>;

export function AdminPayments(){const [status,setStatus]=useState(''),[data,setData]=useState(null),[error,setError]=useState('');const load=useCallback(async()=>{setError('');try{setData(await fetchAdminOrders({paymentStatus:status,limit:50,sort:'newest'}))}catch(e){setError(e.message)}},[status]);useEffect(()=>{queueMicrotask(load)},[load]);const orders=data?.orders||[];const total=orders.filter(o=>o.paymentStatus==='paid').reduce((n,o)=>n+o.total,0);return <section>{title('Finance','Payments','Track Razorpay and cash-on-delivery payment activity.',<select className="na-select" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All payments</option><option value="paid">Paid</option><option value="pending">Pending</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select>)}<Notice error={error}/><div className="na-metric-row"><article><small>Visible transactions</small><strong>{orders.length}</strong></article><article><small>Paid value</small><strong>{money.format(total)}</strong></article><article><small>Pending</small><strong>{orders.filter(o=>o.paymentStatus==='pending').length}</strong></article></div>{!data&&!error?<Load/>:<DataTable headings={['Order','Customer','Provider','Amount','Payment','Date']} rows={orders.map(o=>[o.orderNumber,o.shippingAddress?.fullName||'Customer',o.paymentProvider||'—',money.format(o.total),<Badge key="s" value={o.paymentStatus}/>,date.format(new Date(o.createdAt))])}/>}</section>}

export function AdminInvoices(){const [data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{queueMicrotask(async()=>{try{setData(await fetchAdminOrders({paymentStatus:'paid',limit:50,sort:'newest'}))}catch(e){setError(e.message)}})},[]);const print=async id=>{try{const o=await fetchAdminOrder(id);const popup=window.open('','_blank','width=850,height=900');if(!popup)throw new Error('Allow pop-ups to print invoices.');const items=o.items.map(i=>`<tr><td>${i.name}</td><td>${i.quantity}</td><td>₹${i.unitPrice}</td><td>₹${i.lineTotal}</td></tr>`).join('');popup.document.write(`<!doctype html><title>Invoice ${o.orderNumber}</title><style>body{font:14px Arial;padding:45px;color:#241719}h1{color:#650018}header{display:flex;justify-content:space-between}table{width:100%;border-collapse:collapse;margin:30px 0}th,td{text-align:left;padding:12px;border-bottom:1px solid #ddd}.total{text-align:right;font-size:20px}</style><header><div><h1>SKYRA JEWELLERY</h1><p>Tax Invoice</p></div><div><b>${o.orderNumber}</b><p>${date.format(new Date(o.createdAt))}</p></div></header><p><b>Bill to:</b><br>${o.shippingAddress.fullName}<br>${o.shippingAddress.line1}, ${o.shippingAddress.city}, ${o.shippingAddress.state} ${o.shippingAddress.pincode}</p><table><thead><tr><th>Item</th><th>Qty</th><th>Rate</th><th>Total</th></tr></thead><tbody>${items}</tbody></table><p class="total"><b>Total: ₹${o.total}</b></p><script>window.onload=()=>window.print()</script>`);popup.document.close()}catch(e){setError(e.message)}};const orders=data?.orders||[];return <section>{title('Accounting','GST & Invoices','Generate printable invoices from paid orders.')}<Notice error={error}/>{!data&&!error?<Load/>:<div className="na-card-grid">{orders.map(o=><article className="na-invoice" key={o._id}><div><small>PAID INVOICE</small><h3>{o.orderNumber}</h3><p>{o.shippingAddress?.fullName} · {date.format(new Date(o.createdAt))}</p></div><strong>{money.format(o.total)}</strong><button onClick={()=>print(o._id)}>Print invoice</button></article>)}{!orders.length&&<Empty text="Paid orders will appear here as invoices."/>}</div>}</section>}

export function AdminReports(){const [data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{queueMicrotask(async()=>{try{setData(await fetchDashboard())}catch(e){setError(e.message)}})},[]);if(!data&&!error)return <Load/>;const s=data?.stats||{};return <section>{title('Analytics','Reports','A live summary calculated from orders, customers, products, and payments.')}<Notice error={error}/><div className="na-metric-row"><article><small>Revenue</small><strong>{money.format(s.revenue||0)}</strong></article><article><small>Orders</small><strong>{s.orders||0}</strong></article><article><small>Average order</small><strong>{money.format(s.averageOrderValue||0)}</strong></article><article><small>Customers</small><strong>{s.users||0}</strong></article></div><div className="na-report-grid"><article className="na-module-card"><h2>Monthly revenue</h2>{(data?.revenueChart||[]).map(m=><div className="na-report-line" key={`${m.year}-${m.month}`}><span>{m.label} {m.year}</span><i><b style={{width:`${Math.max(2,(m.total/Math.max(...data.revenueChart.map(x=>x.total),1))*100)}%`}}/></i><strong>{money.format(m.total)}</strong></div>)}</article><article className="na-module-card"><h2>Payment methods</h2>{(data?.paymentOverview||[]).map(p=><div className="na-report-payment" key={p.provider}><span>{p.provider}</span><b>{p.orders} orders</b><strong>{money.format(p.total)}</strong></div>)}</article></div></section>}

export function AdminReviews(){const [filter,setFilter]=useState(''),[data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState('');const load=useCallback(async()=>{try{setData(await fetchAdminReviews({approved:filter,limit:50}))}catch(e){setError(e.message)}},[filter]);useEffect(()=>{queueMicrotask(load)},[load]);const act=async(id,approved)=>{try{await updateAdminReview(id,approved);setNotice(approved?'Review approved.':'Review hidden.');await load()}catch(e){setError(e.message)}};const remove=async id=>{if(!window.confirm('Delete this review permanently?'))return;try{await deleteAdminReview(id);setNotice('Review deleted.');await load()}catch(e){setError(e.message)}};return <section>{title('Community','Reviews','Approve, hide, or remove customer product reviews.',<select className="na-select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All reviews</option><option value="false">Pending</option><option value="true">Approved</option></select>)}<Notice error={error} notice={notice}/>{!data&&!error?<Load/>:<div className="na-review-list">{(data?.reviews||[]).map(r=><article key={r._id}><div className="na-stars">{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</div><h3>{r.title||'Customer review'}</h3><p>{r.comment}</p><small>{r.user?.name||r.user?.email||'Customer'} · {r.product?.name||'Product'} · {date.format(new Date(r.createdAt))}</small><footer><Badge value={r.approved?'approved':'pending'}/><button onClick={()=>act(r._id,!r.approved)}>{r.approved?'Hide':'Approve'}</button><button className="is-danger" onClick={()=>remove(r._id)}>Delete</button></footer></article>)}{!data?.reviews?.length&&<Empty text="No reviews match this filter."/>}</div>}</section>}

function SiteEditor({homepage=false}){const [form,setForm]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState('');useEffect(()=>{queueMicrotask(async()=>{try{const d=await fetchSiteSettings();setForm(d.settings)}catch(e){setError(e.message)}})},[]);const save=async e=>{e.preventDefault();try{const d=await updateSiteSettings({storeName:form.storeName,supportEmail:form.supportEmail||'',supportPhone:form.supportPhone||'',announcement:form.announcement||'',maintenanceMode:Boolean(form.maintenanceMode),taxRate:Number(form.taxRate)||0});setForm(d.settings);setNotice('Store settings saved.')}catch(x){setError(x.message)}};if(!form&&!error)return <Load/>;return <section>{title(homepage?'Storefront':'Configuration',homepage?'Homepage Manager':'Settings',homepage?'Control the storefront announcement and public store identity.':'Manage store contact, tax, and maintenance settings.')}<Notice error={error} notice={notice}/>{form&&<form className="na-form na-module-card" onSubmit={save}><label><span>Store name</span><input value={form.storeName||''} onChange={e=>setForm({...form,storeName:e.target.value})}/></label><label className="is-wide"><span>Announcement bar</span><textarea rows="3" value={form.announcement||''} onChange={e=>setForm({...form,announcement:e.target.value})}/></label>{!homepage&&<><label><span>Support email</span><input type="email" value={form.supportEmail||''} onChange={e=>setForm({...form,supportEmail:e.target.value})}/></label><label><span>Support phone</span><input value={form.supportPhone||''} onChange={e=>setForm({...form,supportPhone:e.target.value})}/></label><label><span>Tax rate (%)</span><input type="number" min="0" max="100" value={form.taxRate||0} onChange={e=>setForm({...form,taxRate:e.target.value})}/></label></>}<label className="na-check"><input type="checkbox" checked={Boolean(form.maintenanceMode)} onChange={e=>setForm({...form,maintenanceMode:e.target.checked})}/><span>Maintenance mode</span></label><button type="submit">Save changes</button></form>}</section>}
export const AdminHomepage=()=> <SiteEditor homepage/>; export const AdminSiteSettings=()=> <SiteEditor/>;

export function AdminShippingManager(){const [form,setForm]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState('');useEffect(()=>{queueMicrotask(async()=>{try{const d=await fetchShippingSettings();setForm(d.shipping)}catch(e){setError(e.message)}})},[]);const save=async e=>{e.preventDefault();try{const d=await updateShippingSettings({freeShippingAll:Boolean(form.freeShippingAll),freeShippingEnabled:Boolean(form.freeShippingEnabled),fixedShippingRate:Number(form.fixedShippingRate)||0,freeShippingThreshold:Number(form.freeShippingThreshold)||0});setForm(d.shipping);setNotice('Shipping rules saved.')}catch(x){setError(x.message)}};return <section>{title('Fulfilment','Shipping','Control checkout delivery charges and free-shipping rules.')}<Notice error={error} notice={notice}/>{!form&&!error?<Load/>:form&&<form className="na-form na-module-card" onSubmit={save}><label><span>Fixed shipping rate</span><input type="number" min="0" value={form.fixedShippingRate} onChange={e=>setForm({...form,fixedShippingRate:e.target.value})}/></label><label><span>Free shipping threshold</span><input type="number" min="0" value={form.freeShippingThreshold} onChange={e=>setForm({...form,freeShippingThreshold:e.target.value})}/></label><label className="na-check"><input type="checkbox" checked={form.freeShippingEnabled} onChange={e=>setForm({...form,freeShippingEnabled:e.target.checked})}/><span>Enable threshold-based free shipping</span></label><label className="na-check"><input type="checkbox" checked={form.freeShippingAll} onChange={e=>setForm({...form,freeShippingAll:e.target.checked})}/><span>Free shipping for every order</span></label><button type="submit">Save shipping rules</button></form>}</section>}

export function AdminCustomers(){const [search,setSearch]=useState(''),[data,setData]=useState(null),[error,setError]=useState('');const load=useCallback(async()=>{try{setData(await fetchAdminUsers({search,limit:50}))}catch(e){setError(e.message)}},[search]);useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[load]);useEffect(()=>{const t=setInterval(load,15000);return()=>clearInterval(t)},[load]);return <section>{title('Community','Customers','Search customer profiles and see who is online now.',<input className="na-search-input" placeholder="Search name or email" value={search} onChange={e=>setSearch(e.target.value)}/>)}<Notice error={error}/>{!data&&!error?<Load/>:<DataTable headings={['Customer','Email','Joined','Status','Online']} rows={(data?.users||[]).map(u=>[u.name||'Customer',u.email,date.format(new Date(u.createdAt)),<Badge key="s" value={u.active===false?'disabled':'active'}/>,<Badge key="o" value={u.online?'online':'offline'}/>])}/>}</section>}

export function AdminRoles(){const [data,setData]=useState(null),[email,setEmail]=useState(''),[role,setRole]=useState('admin'),[error,setError]=useState(''),[notice,setNotice]=useState('');const load=useCallback(async()=>{try{setData(await fetchAdmins())}catch(e){setError(e.message)}},[]);useEffect(()=>{queueMicrotask(load)},[load]);const add=async e=>{e.preventDefault();try{await createAdministrator({email,role});setEmail('');setNotice('Administrator added.');await load()}catch(x){setError(x.message)}};const toggle=async a=>{try{await updateAdministrator(a._id,{active:a.active===false});await load()}catch(e){setError(e.message)}};return <section>{title('Security','Admin Roles','Grant and manage administrator access.')}<Notice error={error} notice={notice}/><form className="na-inline-form" onSubmit={add}><input type="email" required placeholder="Approved Gmail account" value={email} onChange={e=>setEmail(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value)}><option value="manager">Manager</option><option value="admin">Admin</option><option value="superadmin">Superadmin</option></select><button>Add administrator</button></form>{!data&&!error?<Load/>:<DataTable headings={['Name','Email','Role','Status','Action']} rows={(data?.admins||[]).map(a=>[a.user?.name||'Administrator',a.user?.email,a.role,<Badge key="s" value={a.active?'active':'disabled'}/>,<button className="na-table-button" key="b" onClick={()=>toggle(a)}>{a.active?'Disable':'Enable'}</button>])}/>}</section>}

export function AdminSearchResults(){const [params]=useSearchParams(),q=params.get('q')||'';const [data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{queueMicrotask(async()=>{try{const [products,orders,users]=await Promise.all([fetchAdminProducts({search:q,limit:8}),fetchAdminOrders({search:q,limit:8}),fetchAdminUsers({search:q,limit:8})]);setData({products:products.products||[],orders:orders.orders||[],users:users.users||[]})}catch(e){setError(e.message)}})},[q]);return <section>{title('Search','Results',`Results for “${q}”`)}<Notice error={error}/>{!data&&!error?<Load/>:<div className="na-search-results"><Result title="Products" to="/admin/products" items={data.products.map(x=>({key:x._id,title:x.name,copy:x.sku||x.slug}))}/><Result title="Orders" to="/admin/orders" items={data.orders.map(x=>({key:x._id,title:x.orderNumber,copy:`${x.shippingAddress?.fullName} · ${money.format(x.total)}`}))}/><Result title="Customers" to="/admin/users" items={data.users.map(x=>({key:x._id,title:x.name||'Customer',copy:x.email}))}/></div>}</section>}

function Result({title:heading,to,items}){return <article className="na-module-card"><h2>{heading}</h2>{items.map(i=><div className="na-search-result" key={i.key}><div><strong>{i.title}</strong><small>{i.copy}</small></div><Link to={to}>Open →</Link></div>)}{!items.length&&<Empty text={`No ${heading.toLowerCase()} found.`}/>}</article>}
function DataTable({headings,rows}){return <div className="na-module-card na-table-wrap"><table className="na-table"><thead><tr>{headings.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>{!rows.length&&<Empty text="No records found."/>}</div>}
function Badge({value}){return <span className={`na-badge is-${value}`}>{value}</span>}
function Empty({text}){return <div className="na-empty">◇<p>{text}</p></div>}
