import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext.jsx';
import { fetchDashboard } from '../../services/adminApi.js';
import { NewAdminIcon } from '../../components/admin-new/NewAdminLayout.jsx';

const money=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0});
const compact=new Intl.NumberFormat('en-IN',{notation:'compact',maximumFractionDigits:1});
const dateFormat=new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'});
const monthNames=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

function StatCard({icon,label,value,note,tone}){return <article className="new-admin-stat"><span className="new-admin-stat__icon"><NewAdminIcon name={icon}/></span><div><small>{label}</small><strong>{value}</strong><p className={tone||''}>{note}</p></div></article>}
function RevenueChart({points=[]}){const values=points.map(p=>p.total||0),max=Math.max(...values,1),coords=values.map((v,i)=>`${32+i*(568/Math.max(values.length-1,1))},${180-(v/max)*140}`),line=coords.join(' '),area=`32,184 ${line} 600,184`;return <div className="new-admin-chart"><div className="new-admin-chart__grid"><span>₹{compact.format(max)}</span><span>₹{compact.format(max*.66)}</span><span>₹{compact.format(max*.33)}</span><span>₹0</span></div><svg viewBox="0 0 632 208" preserveAspectRatio="none" aria-label="Monthly revenue chart"><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#9f1530" stopOpacity=".34"/><stop offset="1" stopColor="#9f1530" stopOpacity="0"/></linearGradient></defs><polygon points={area} fill="url(#revenueFill)"/><polyline points={line} fill="none" stroke="#7c071e" strokeWidth="3" strokeLinejoin="round"/>{coords.map((point,i)=>{const [cx,cy]=point.split(',');return <circle key={i} cx={cx} cy={cy} r="4" fill="#7c071e"/>})}</svg><div className="new-admin-chart__months">{points.map((p,i)=><span key={`${p.month}-${i}`}>{p.label||monthNames[(p.month||1)-1]}</span>)}</div></div>}
function PaymentChart({items=[],total=0}){const colors=['#79051d','#c8892e','#ebcda2','#8d6d55'];let offset=0;const gradient=items.length?items.map((item,i)=>{const start=offset;offset+=total?item.total/total*100:0;return `${colors[i%colors.length]} ${start}% ${offset}%`}).join(', '):'#eadfd5 0 100%';return <div className="new-admin-payments"><div className="new-admin-donut" style={{background:`conic-gradient(${gradient})`}}><span>Total<strong>{money.format(total)}</strong></span></div><ul>{items.map((item,i)=><li key={item.provider}><i style={{background:colors[i%colors.length]}}/><span>{item.provider?.toUpperCase()}</span><b>{total?Math.round(item.total/total*100):0}%</b><small>{money.format(item.total)}</small></li>)}</ul></div>}

export default function NewAdminDashboard(){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''); const {profile,user}=useAuth();
 const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await fetchDashboard())}catch(err){setError(err.message)}finally{setLoading(false)}},[]); useEffect(()=>{queueMicrotask(load)},[load]);
 const d=data||{},s=d.stats||{},orders=d.recentOrders||[],lowStock=d.lowStock||[],top=d.topProducts||[],payments=d.paymentOverview||[];
 const paymentTotal=payments.reduce((sum,item)=>sum+(item.total||0),0);
 if(loading)return <div className="new-admin-loading"><div/><div/><div/><div/><section/></div>;
 return <div className="new-admin-dashboard">
  <header className="new-admin-heading"><div><h1>Dashboard</h1><p>Welcome back, {profile?.name||user?.displayName||'Admin'}! Here’s what’s happening with your store.</p></div><button onClick={load}>↻ Refresh</button></header>
  {error&&<div className="new-admin-error">Live dashboard data could not load: {error}. Showing an empty dashboard. <button onClick={load}>Try again</button></div>}
  <section className="new-admin-stats"><StatCard icon="payments" label="Total Revenue" value={money.format(s.revenue||0)} note="Paid order value" tone="positive"/><StatCard icon="products" label="Total Orders" value={compact.format(s.orders||0)} note="All-time orders" tone="positive"/><StatCard icon="orders" label="Pending Orders" value={s.pendingOrders||0} note="View all pending"/><StatCard icon="reports" label="Low Stock Alert" value={`${lowStock.length} items`} note="View all alerts"/><StatCard icon="invoices" label="Today’s Sales" value={money.format(s.todaySales||0)} note="Paid today" tone="positive"/></section>
  <section className="new-admin-analytics"><article className="new-admin-card new-admin-revenue"><div className="new-admin-card__head"><h2>Revenue Overview</h2><select aria-label="Revenue period"><option>This Year</option></select></div><RevenueChart points={d.revenueChart||[]}/></article><article className="new-admin-card"><div className="new-admin-card__head"><h2>Payment Overview</h2></div><PaymentChart items={payments} total={paymentTotal}/></article><aside><div className="new-admin-date">▣ <span>{dateFormat.format(new Date())}</span><b>⌄</b></div><div className="new-admin-card new-admin-actions"><h2>Quick Actions</h2>{[['＋','Add New Product','/admin/products'],['▤','View Orders','/admin/orders'],['▧','Manage Shipping','/admin/shipping'],['⊞','Add New Category','/admin/categories']].map(([icon,label,to])=><Link to={to} key={label}><i>{icon}</i><span>{label}</span><b>›</b></Link>)}</div><div className="new-admin-ai"><span>✦</span><h2>SKYRA Insights <b>Live</b></h2><p>Your dashboard uses real store data for revenue, stock, payments, and sales activity.</p></div></aside></section>
  <section className="new-admin-bottom"><article className="new-admin-card"><div className="new-admin-card__head"><h2>Recent Orders</h2><Link to="/admin/orders">View All Orders</Link></div><div className="new-admin-table-wrap"><table><thead><tr><th>Order ID</th><th>Customer</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>{orders.length?orders.slice(0,6).map(o=><tr key={o._id}><td>{o.orderNumber}</td><td>{o.user?.name||o.shippingAddress?.fullName||'Customer'}</td><td>{money.format(o.total||0)}</td><td><span className={`status-${o.status}`}>{o.status}</span></td><td>{dateFormat.format(new Date(o.createdAt))}</td></tr>):<tr><td colSpan="5" className="new-admin-empty">No orders yet</td></tr>}</tbody></table></div></article><article className="new-admin-card"><div className="new-admin-card__head"><h2>Top Selling Products</h2><Link to="/admin/products">View All Products →</Link></div><div className="new-admin-products">{top.length?top.slice(0,5).map((p,i)=><div key={p.product||p.name}><span>{p.image?<img src={p.image} alt=""/>:i+1}</span><div><strong>{p.name}</strong><small>{p.sold} Sold</small></div><b>{money.format(p.revenue||0)}</b></div>):<div className="new-admin-empty">Sales will appear here after your first order.</div>}</div></article><article className="new-admin-card new-admin-summary"><h2>Store Summary</h2>{[['products','Total Products',s.products||0],['customers','Total Customers',s.users||0],['orders','Pending Orders',s.pendingOrders||0],['payments','Average Order Value',money.format(s.averageOrderValue||0)],['reports','Low Stock Items',lowStock.length]].map(([icon,label,value])=><div key={label}><NewAdminIcon name={icon} size={17}/><span>{label}</span><b>{value}</b></div>)}</article></section>
 </div>;
}
