import { useEffect, useMemo, useState } from 'react';
import { fetchAdminOrder, updateAdminOrderStatus } from '../../services/adminApi.js';
import { Modal, PageState } from './AdminControls.jsx';
import { statusClass, statusLabel } from '../../utils/orderUtils.js';

const money=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2});
const dateTime=new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});
const transitions={pending:['confirmed','processing','cancelled'],confirmed:['processing','cancelled'],processing:['packed','cancelled'],packed:['shipped','cancelled'],shipped:['in_transit','out_for_delivery','delivered'],in_transit:['out_for_delivery','delivered'],out_for_delivery:['delivered'],delivered:['completed'],completed:[],cancelled:[]};

export default function OrderDetailModal({orderId,onClose,onChanged,hideStatusHistory=false}){
  const [order,setOrder]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[status,setStatus]=useState(''),[note,setNote]=useState(''),[estimate,setEstimate]=useState(''),[updating,setUpdating]=useState(false),[success,setSuccess]=useState('');
  useEffect(()=>{let active=true;queueMicrotask(async()=>{try{const data=await fetchAdminOrder(orderId);if(active){setOrder(data);setEstimate(data.estimatedDeliveryDate?new Date(data.estimatedDeliveryDate).toISOString().slice(0,10):'');}}catch(err){if(active)setError(err.message);}finally{if(active)setLoading(false);}});return()=>{active=false;};},[orderId]);
  const nextStatuses=useMemo(()=>transitions[order?.status]||[],[order]);
  const updateStatus=async(event)=>{event.preventDefault();if(!status)return;setUpdating(true);setError('');setSuccess('');try{const updated=await updateAdminOrderStatus(order._id,{status,note:note.trim()||undefined,estimatedDeliveryDate:estimate?new Date(`${estimate}T12:00:00.000Z`).toISOString():undefined});setOrder((current)=>({...current,...updated}));setStatus('');setNote('');setSuccess('Order status updated.');onChanged(updated);}catch(err){setError(err.message);}finally{setUpdating(false);}};
  return <Modal open onClose={updating?()=>{}:onClose} title={order?.orderNumber||'Order details'} eyebrow="Order record" wide>{loading?<div className="admin-order-detail-loading"><div className="admin-spinner"/><p>Loading order details…</p></div>:error&&!order?<PageState type="error" title="Unable to load order" message={error}/>:order&&<div className="admin-order-detail">{error&&<div className="admin-alert admin-alert--error">{error}</div>}{success&&<div className="admin-alert admin-alert--success">{success}</div>}<div className="admin-order-hero"><div><span className={statusClass(order.status)}>{statusLabel(order.status)}</span><h2>{order.orderNumber}</h2><p>Placed {dateTime.format(new Date(order.createdAt))}</p></div><div className="admin-order-hero__amount"><small>Grand total</small><strong>{money.format(order.total)}</strong><span className={statusClass(order.paymentStatus)}>{statusLabel(order.paymentStatus)} payment</span></div></div>
    <div className="admin-order-info-grid"><section><p className="admin-eyebrow">Customer</p><h3>{order.shippingAddress.fullName}</h3><p>{order.shippingAddress.email}</p><p>{order.shippingAddress.phone}</p>{order.shippingAddress.secondaryPhone&&<p>Alternative: {order.shippingAddress.secondaryPhone}</p>}</section><section><p className="admin-eyebrow">Shipping address</p><h3>{order.shippingAddress.line1}</h3>{order.shippingAddress.line2&&<p>{order.shippingAddress.line2}</p>}<p>{order.shippingAddress.city}, {order.shippingAddress.state} – {order.shippingAddress.pincode}</p>{order.shippingAddress.notes&&<p className="admin-order-note">“{order.shippingAddress.notes}”</p>}</section><section><p className="admin-eyebrow">Delivery</p><h3>{order.estimatedDeliveryDate?dateTime.format(new Date(order.estimatedDeliveryDate)):'Not estimated yet'}</h3><p>{statusLabel(order.status)}</p></section></div>
    <section className="admin-order-section"><div className="admin-order-section__head"><div><p className="admin-eyebrow">Items</p><h3>Ordered products</h3></div><span>{order.items.length} line item{order.items.length===1?'':'s'}</span></div><div className="admin-order-items">{order.items.map((item,index)=><article key={`${item.product}-${index}`}>{item.image?<img src={item.image} alt=""/>:<span className="admin-order-item-blank">◇</span>}<div><strong>{item.name}</strong><small>{item.variantSku?`Variant ${item.variantSku}`:item.sku||'Standard piece'}</small><span>{money.format(item.unitPrice)} × {item.quantity}</span></div><b>{money.format(item.lineTotal)}</b></article>)}</div></section>
    <div className={`admin-order-bottom${hideStatusHistory?' admin-order-bottom--summary-only':''}`}>{!hideStatusHistory&&<section className="admin-order-section"><p className="admin-eyebrow">Status history</p><div className="admin-timeline">{[...(order.statusHistory||[])].reverse().map((entry,index)=><div key={`${entry.status}-${entry.changedAt}-${index}`}><span/><article><strong>{statusLabel(entry.status)}</strong><time>{dateTime.format(new Date(entry.changedAt))}</time>{entry.note&&<p>{entry.note}</p>}<small>{entry.changedBy?.name?`Changed by ${entry.changedBy.name}`:'System update'}</small></article></div>)}</div></section>}<section className="admin-order-summary"><p className="admin-eyebrow">Order totals</p><dl><div><dt>Subtotal</dt><dd>{money.format(order.subtotal)}</dd></div><div><dt>Shipping</dt><dd>{order.shippingCost?money.format(order.shippingCost):'Free'}</dd></div>{order.tax>0&&<div><dt>Tax</dt><dd>{money.format(order.tax)}</dd></div>}<div className="admin-order-summary__total"><dt>Grand total</dt><dd>{money.format(order.total)}</dd></div></dl></section></div>
    <section className="admin-order-update"><div><p className="admin-eyebrow">Update workflow</p><h3>Move this order forward</h3></div>{nextStatuses.length?<form onSubmit={updateStatus}><label className="admin-field"><span>New status</span><select value={status} onChange={(event)=>setStatus(event.target.value)} required><option value="">Select status</option>{nextStatuses.map((item)=><option value={item} key={item}>{statusLabel(item)}</option>)}</select></label><label className="admin-field"><span>Estimated delivery</span><input type="date" value={estimate} onChange={(event)=>setEstimate(event.target.value)}/></label><label className="admin-field admin-field--note"><span>Internal note</span><input value={note} maxLength="300" onChange={(event)=>setNote(event.target.value)} placeholder="Optional update note"/></label><button className="admin-button admin-button--primary" disabled={updating}>{updating?'Updating…':'Update status'}</button></form>:<p className="admin-order-update__complete">This order has reached its final status.</p>}</section>
  </div>}</Modal>;
}
