import { useMemo, useState } from 'react';
import { deleteAdminImage, uploadAdminImages } from '../../services/adminApi.js';
import { Modal, Toggle } from './AdminControls.jsx';
import { resolveImageUrl } from '../../utils/imageUrl.js';

const slugify = (value = '') => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
const specLabels = ['Set Includes', 'Material', 'Main Stone', 'Center Stone', 'Accent Stones', 'Stones', 'Setting', 'Finish', 'Chain', 'Chain Type', 'Closure', 'Pendant Size', 'Size', 'Weight', 'Design', 'Style', 'Motif', 'Color', 'Cut', 'Length', 'Band Type', 'Occasion', 'Pieces'];
const blank = { name: '', slug: '', description: '', category: '', price: '', discount: 0, stock: 0, active: true, featured: false, hot: false, newArrival: false, images: [], groups: [], specifications: [] };
const groupsFromVariants = (variants = []) => Object.values(variants.reduce((result, variant) => { const key = variant.group || 'Option'; result[key] ||= { id: crypto.randomUUID(), name: key, values: [] }; result[key].values.push({ id: crypto.randomUUID(), value: variant.value || variant.name || '', sku: variant.sku || '', stock: variant.stock ?? '', price: variant.price ?? '' }); return result; }, {}));
const initialForm = (product) => { if (!product) return { ...blank, images: [], groups: [], specifications: [] }; const sourceImages = product.images || []; const hasPrimary = sourceImages.some((image) => image.isPrimary); return { name: product.name || '', slug: product.slug || '', description: product.description || '', category: product.category?._id || product.category || '', price: product.price ?? '', discount: product.discount ?? 0, stock: product.stock ?? 0, active: product.active !== false, featured: Boolean(product.featured), hot: Boolean(product.hot), newArrival: Boolean(product.newArrival), images: sourceImages.map((image, index) => ({ ...image, isPrimary: image.isPrimary || (!hasPrimary && index === 0) })), groups: groupsFromVariants(product.variants), specifications: (product.specifications || []).map((spec) => ({ id: crypto.randomUUID(), label: spec.label || '', value: spec.value || '' })) }; };

export default function ProductFormModal({ open, product, categories, onClose, onSave, stockOnly = false }) {
  const [form, setForm] = useState(() => initialForm(product)), [slugEdited, setSlugEdited] = useState(Boolean(product)), [imageUrl, setImageUrl] = useState('');
  const [uploading, setUploading] = useState(false), [uploadError, setUploadError] = useState(''), [saving, setSaving] = useState(false), [error, setError] = useState(''), [fieldErrors, setFieldErrors] = useState({});
  const [newPublicIds, setNewPublicIds] = useState([]), [removedPublicIds, setRemovedPublicIds] = useState([]);
  const primaryCount = useMemo(() => form.images.filter((image) => image.isPrimary).length, [form.images]);
  const set = (key, value) => { setForm((current) => ({ ...current, [key]: value })); setFieldErrors((current) => ({ ...current, [key]: '' })); };
  const handleName = (value) => { setForm((current) => ({ ...current, name: value, slug: slugEdited ? current.slug : slugify(value) })); setFieldErrors((current) => ({ ...current, name: '', slug: '' })); };
  const addManualImage = () => { const url = imageUrl.trim(); try { new URL(url); } catch { setUploadError('Enter a complete image URL, including https://'); return; } setForm((current) => ({ ...current, images: [...current.images, { url, alt: current.name, isPrimary: current.images.length === 0 }] })); setImageUrl(''); setUploadError(''); };
  const uploadFiles = async (event) => { const files = [...event.target.files]; event.target.value = ''; if (!files.length) return; setUploading(true); setUploadError(''); try { const result = await uploadAdminImages(files); const images = result.images || []; setNewPublicIds((current) => [...current, ...images.map((image) => image.publicId).filter(Boolean)]); setForm((current) => ({ ...current, images: [...current.images, ...images.map((image, index) => ({ ...image, alt: current.name, isPrimary: current.images.length === 0 && index === 0 }))] })); } catch (err) { setUploadError(err.message); } finally { setUploading(false); } };
  const removeImage = async (index) => { const image = form.images[index]; setForm((current) => { const remaining = current.images.filter((_, itemIndex) => itemIndex !== index); if (image.isPrimary && remaining[0]) remaining[0] = { ...remaining[0], isPrimary: true }; return { ...current, images: remaining }; }); if (!image.publicId) return; if (newPublicIds.includes(image.publicId)) { setNewPublicIds((current) => current.filter((id) => id !== image.publicId)); deleteAdminImage(image.publicId).catch(() => {}); } else setRemovedPublicIds((current) => [...current, image.publicId]); };
  const makePrimary = (index) => setForm((current) => ({ ...current, images: current.images.map((image, itemIndex) => ({ ...image, isPrimary: itemIndex === index })) }));
  const addGroup = () => set('groups', [...form.groups, { id: crypto.randomUUID(), name: '', values: [{ id: crypto.randomUUID(), value: '', sku: '', stock: '', price: '' }] }]);
  const updateGroup = (groupId, field, value) => set('groups', form.groups.map((group) => group.id === groupId ? { ...group, [field]: value } : group));
  const removeGroup = (groupId) => set('groups', form.groups.filter((group) => group.id !== groupId));
  const addValue = (groupId) => set('groups', form.groups.map((group) => group.id === groupId ? { ...group, values: [...group.values, { id: crypto.randomUUID(), value: '', sku: '', stock: '', price: '' }] } : group));
  const updateValue = (groupId, valueId, field, value) => set('groups', form.groups.map((group) => group.id === groupId ? { ...group, values: group.values.map((item) => item.id === valueId ? { ...item, [field]: value } : item) } : group));
  const removeValue = (groupId, valueId) => set('groups', form.groups.map((group) => group.id === groupId ? { ...group, values: group.values.filter((item) => item.id !== valueId) } : group));
  const addSpec = (label = '') => set('specifications', [...form.specifications, { id: crypto.randomUUID(), label, value: '' }]);
  const updateSpec = (id, field, value) => set('specifications', form.specifications.map((spec) => spec.id === id ? { ...spec, [field]: value } : spec));
  const removeSpec = (id) => set('specifications', form.specifications.filter((spec) => spec.id !== id));
  const addPresetSpec = (label) => { if (!form.specifications.some((spec) => spec.label.toLowerCase() === label.toLowerCase())) addSpec(label); };
  const submit = async (event) => { event.preventDefault(); setError(''); if(stockOnly){setSaving(true);try{await onSave({stock:Number(form.stock||0)},product?._id);onClose();}catch(err){setError(err.message);}finally{setSaving(false);}return;} const errors={}; if(form.name.trim().length<2)errors.name='Enter at least 2 characters.';if(!form.slug)errors.slug='A product slug is required.';if(!form.category)errors.category='Choose a category.';if(form.price===''||Number(form.price)<0)errors.price='Enter a valid price.';setFieldErrors(errors);if(Object.keys(errors).length){setError('Complete the highlighted required fields.');return;} const incompleteGroup = form.groups.some((group) => !group.name.trim() || !group.values.length || group.values.some((item) => !item.value.trim())); if (incompleteGroup) { setError('Every variant group needs a name and at least one named value.'); return; } const incompleteSpec = form.specifications.some((spec) => spec.label.trim() && !spec.value.trim()); if (incompleteSpec) { setError('Every specification with a label needs a value.'); return; } const variants = form.groups.flatMap((group) => group.values.map((item) => ({ group: group.name.trim(), value: item.value.trim(), name: item.value.trim(), ...(item.sku.trim() ? { sku: item.sku.trim() } : {}), ...(item.stock !== '' ? { stock: Number(item.stock) } : {}), ...(item.price !== '' ? { price: Number(item.price) } : {}), active: true }))); const specifications = form.specifications.filter((spec) => spec.label.trim() && spec.value.trim()).map((spec) => ({ label: spec.label.trim(), value: spec.value.trim() })); const payload = { name: form.name.trim(), slug: form.slug.trim(), description: form.description.trim(), category: form.category, price: Number(form.price), discount: Number(form.discount || 0), stock: Number(form.stock || 0), active: form.active, featured: form.featured, hot: form.hot, newArrival: form.newArrival, specifications, images: form.images.map((image, index) => ({ url: image.url, ...(image.publicId ? { publicId: image.publicId } : {}), alt: image.alt || form.name.trim(), isPrimary: primaryCount ? image.isPrimary : index === 0 })), variants };
    setSaving(true); try { await onSave(payload, product?._id); await Promise.allSettled(removedPublicIds.map(deleteAdminImage)); onClose(); } catch (err) { setError(err.message); } finally { setSaving(false); }
  };
  if (stockOnly) return <Modal open={open} onClose={saving ? () => {} : onClose} title={product?.name || 'Update stock'} eyebrow="Stock editor"><form className="admin-form" onSubmit={submit}>{error&&<div className="admin-alert admin-alert--error">{error}</div>}<label className="admin-field"><span>Base stock</span><input autoFocus type="number" min="0" step="1" value={form.stock} onChange={(event)=>set('stock',event.target.value)}/></label><div className="admin-inline-empty">This role can only update product stock from this editor. Status and badges are controlled from the product table.</div><footer className="admin-form-actions"><button type="button" className="admin-button admin-button--secondary" onClick={onClose} disabled={saving}>Cancel</button><button type="submit" className="admin-button admin-button--primary" disabled={saving}>{saving?'Saving stock…':'Save stock'}</button></footer></form></Modal>;
  return <Modal open={open} onClose={saving ? () => {} : onClose} title={product ? 'Edit product' : 'Add a new product'} eyebrow="Catalogue editor" wide><form className="admin-form" onSubmit={submit}>
    {error&&<div className="admin-alert admin-alert--error">{error}</div>}
    <div className="admin-form-grid"><label className={`admin-field${fieldErrors.name?' admin-field--invalid':''}`}><span>Product name *</span><input required aria-invalid={Boolean(fieldErrors.name)} value={form.name} onChange={(event)=>handleName(event.target.value)} placeholder="Eterna pearl necklace"/>{fieldErrors.name&&<small>{fieldErrors.name}</small>}</label><label className={`admin-field${fieldErrors.slug?' admin-field--invalid':''}`}><span>Slug *</span><input required aria-invalid={Boolean(fieldErrors.slug)} value={form.slug} onChange={(event)=>{setSlugEdited(true);set('slug',slugify(event.target.value));}} placeholder="eterna-pearl-necklace"/>{fieldErrors.slug&&<small>{fieldErrors.slug}</small>}</label><label className="admin-field admin-field--full"><span>Description</span><textarea rows="5" value={form.description} onChange={(event)=>set('description',event.target.value)} placeholder="Materials, story, care details…"/></label><label className={`admin-field${fieldErrors.category?' admin-field--invalid':''}`}><span>Category *</span><select required aria-invalid={Boolean(fieldErrors.category)} value={form.category} onChange={(event)=>set('category',event.target.value)}><option value="">Choose a category</option>{categories.map((category)=><option value={category._id} key={category._id} disabled={!category.active&&category._id!==form.category}>{category.name}{category.active?'':' (inactive)'}</option>)}</select>{fieldErrors.category&&<small>{fieldErrors.category}</small>}</label><label className={`admin-field${fieldErrors.price?' admin-field--invalid':''}`}><span>Base price (₹) *</span><input required aria-invalid={Boolean(fieldErrors.price)} type="number" min="0" step="0.01" value={form.price} onChange={(event)=>set('price',event.target.value)}/>{fieldErrors.price&&<small>{fieldErrors.price}</small>}</label><label className="admin-field"><span>Discount (%)</span><input type="number" min="0" max="100" value={form.discount} onChange={(event)=>set('discount',event.target.value)}/></label><label className="admin-field"><span>Base stock</span><input type="number" min="0" step="1" value={form.stock} onChange={(event)=>set('stock',event.target.value)}/></label></div>
    <div className="admin-form-switches"><Toggle checked={form.active} onChange={(value)=>set('active',value)} label="Active"/><Toggle checked={form.featured} onChange={(value)=>set('featured',value)} label="Featured"/><Toggle checked={form.hot} onChange={(value)=>set('hot',value)} label="Hot"/><Toggle checked={form.newArrival} onChange={(value)=>set('newArrival',value)} label="New"/></div>
    <section className="admin-form-section"><div className="admin-form-section__head"><div><h3>Product images</h3><p>Upload JPEG, PNG, or WebP files, or paste a hosted image URL.</p></div><label className={`admin-upload-button${uploading?' admin-upload-button--busy':''}`}><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={uploadFiles} disabled={uploading}/>{uploading?'Uploading…':'Upload images'}</label></div><div className="admin-url-row"><input value={imageUrl} onChange={(event)=>setImageUrl(event.target.value)} placeholder="https://example.com/product-image.jpg"/><button type="button" className="admin-button admin-button--secondary" onClick={addManualImage}>Add URL</button></div>{uploadError&&<div className="admin-alert admin-alert--error">{uploadError}</div>}{form.images.length?<div className="admin-image-grid">{form.images.map((image,index)=><figure className={`admin-image-card${image.isPrimary?' admin-image-card--primary':''}`} key={`${image.url}-${index}`}><img src={resolveImageUrl(image.url)} alt={image.alt||form.name}/><figcaption><button type="button" onClick={()=>makePrimary(index)}>{image.isPrimary?'Primary image':'Make primary'}</button><button type="button" onClick={()=>removeImage(index)}>Remove</button></figcaption></figure>)}</div>:<div className="admin-inline-empty">No product images added yet.</div>}</section>
    <section className="admin-form-section"><div className="admin-form-section__head"><div><h3>Specifications</h3><p>Edit product details such as set contents, material, stone, finish, chain, closure, size, and weight.</p></div><button type="button" className="admin-button admin-button--secondary" onClick={()=>addSpec()}>+ Add spec</button></div><div className="admin-spec-presets">{specLabels.map((label)=><button type="button" key={label} onClick={()=>addPresetSpec(label)}>{label}</button>)}</div>{form.specifications.length===0?<div className="admin-inline-empty">No specifications yet. Add the details customers need before buying.</div>:<div className="admin-spec-list">{form.specifications.map((spec)=><div className="admin-spec-row" key={spec.id}><input list="admin-spec-labels" value={spec.label} onChange={(event)=>updateSpec(spec.id,'label',event.target.value)} placeholder="Material"/><input value={spec.value} onChange={(event)=>updateSpec(spec.id,'value',event.target.value)} placeholder="Alloy (Silver-Plated)"/><button type="button" onClick={()=>removeSpec(spec.id)} aria-label="Remove specification">×</button></div>)}</div>}<datalist id="admin-spec-labels">{specLabels.map((label)=><option value={label} key={label}/>)}</datalist></section>
    <section className="admin-form-section"><div className="admin-form-section__head"><div><h3>Variants</h3><p>Add groups such as Size, Material, or Color, then define their values.</p></div><button type="button" className="admin-button admin-button--secondary" onClick={addGroup}>+ Add group</button></div>{form.groups.length===0?<div className="admin-inline-empty">No variants. Base price and stock will be used.</div>:<div className="admin-variant-groups">{form.groups.map((group)=><article className="admin-variant-group" key={group.id}><div className="admin-variant-group__head"><label className="admin-field"><span>Group name</span><input value={group.name} onChange={(event)=>updateGroup(group.id,'name',event.target.value)} placeholder="Size"/></label><button type="button" className="admin-text-danger" onClick={()=>removeGroup(group.id)}>Remove group</button></div><div className="admin-variant-table"><div className="admin-variant-table__header"><span>Value *</span><span>SKU</span><span>Stock</span><span>Price override</span><span/></div>{group.values.map((item)=><div className="admin-variant-row" key={item.id}><input value={item.value} onChange={(event)=>updateValue(group.id,item.id,'value',event.target.value)} placeholder="Medium"/><input value={item.sku} onChange={(event)=>updateValue(group.id,item.id,'sku',event.target.value.toUpperCase())} placeholder="Optional"/><input type="number" min="0" value={item.stock} onChange={(event)=>updateValue(group.id,item.id,'stock',event.target.value)} placeholder="0"/><input type="number" min="0" step="0.01" value={item.price} onChange={(event)=>updateValue(group.id,item.id,'price',event.target.value)} placeholder="Base"/><button type="button" onClick={()=>removeValue(group.id,item.id)} aria-label="Remove variant">×</button></div>)}</div><button type="button" className="admin-add-value" onClick={()=>addValue(group.id)}>+ Add variant value</button></article>)}</div>}</section>
    <footer className="admin-form-actions"><button type="button" className="admin-button admin-button--secondary" onClick={onClose} disabled={saving}>Cancel</button><button type="submit" className="admin-button admin-button--primary" disabled={saving||uploading}>{saving?'Saving product…':product?'Save changes':'Create product'}</button></footer>
  </form></Modal>;
}
