import { useCallback, useEffect, useState } from 'react';
import { archiveAdminCategory, createAdminCategory, deleteAdminImage, fetchAdminCategories, updateAdminCategory, uploadAdminImages } from '../../services/adminApi.js';
import { useAuth } from '../../context/AuthContext.jsx';
import { ConfirmModal, Modal, PageState, Toggle } from '../../components/admin/AdminControls.jsx';

const slugify=(value='')=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const empty={name:'',slug:'',description:'',image:null,active:true,sortOrder:0};

function CategoryForm({open,category,onClose,onSave}){
  const [form,setForm]=useState(()=>category?{name:category.name||'',slug:category.slug||'',description:category.description||'',image:category.image||null,active:category.active!==false,sortOrder:category.sortOrder||0}:empty),[slugEdited,setSlugEdited]=useState(Boolean(category)),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[newPublicIds,setNewPublicIds]=useState([]),[removedPublicIds,setRemovedPublicIds]=useState([]);
  const update=(key,value)=>setForm((current)=>({...current,[key]:value}));
  const uploadImage=async(event)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;setUploading(true);setError('');try{const result=await uploadAdminImages([file]);const image=result.images?.[0];if(!image)throw new Error('The image could not be uploaded.');if(form.image?.publicId){if(newPublicIds.includes(form.image.publicId)){deleteAdminImage(form.image.publicId).catch(()=>{});setNewPublicIds((ids)=>ids.filter((id)=>id!==form.image.publicId));}else setRemovedPublicIds((ids)=>[...ids,form.image.publicId]);}setNewPublicIds((ids)=>image.publicId?[...ids,image.publicId]:ids);update('image',{url:image.url,publicId:image.publicId,alt:form.name||category?.name||'Category'});}catch(err){setError(err.message);}finally{setUploading(false);}};
  const close=()=>{newPublicIds.forEach((id)=>deleteAdminImage(id).catch(()=>{}));onClose();};
  const submit=async(event)=>{event.preventDefault();if(!form.name.trim()||!form.slug){setError('Name and slug are required.');return;}setSaving(true);setError('');try{await onSave({...form,name:form.name.trim(),slug:form.slug.trim(),description:form.description.trim(),image:form.image?{...form.image,alt:form.image.alt||form.name.trim()}:undefined,sortOrder:Number(form.sortOrder)},category?._id);await Promise.allSettled(removedPublicIds.map(deleteAdminImage));onClose();}catch(err){setError(err.message);}finally{setSaving(false);}};
  return <Modal open={open} onClose={saving||uploading?()=>{}:close} title={category?'Edit category':'Add category'} eyebrow="Homepage category artwork"><form className="admin-form" onSubmit={submit}>{error&&<div className="admin-alert admin-alert--error">{error}</div>}<div className="admin-form-grid"><label className="admin-field admin-field--full"><span>Category name *</span><input value={form.name} onChange={(event)=>{const value=event.target.value;setForm((current)=>({...current,name:value,slug:slugEdited?current.slug:slugify(value)}));}} placeholder="Necklaces"/></label><label className="admin-field"><span>Slug *</span><input value={form.slug} onChange={(event)=>{setSlugEdited(true);update('slug',slugify(event.target.value));}} placeholder="necklaces"/></label><label className="admin-field"><span>Display order</span><input type="number" step="1" value={form.sortOrder} onChange={(event)=>update('sortOrder',event.target.value)}/></label><label className="admin-field admin-field--full"><span>Description</span><textarea rows="5" value={form.description} onChange={(event)=>update('description',event.target.value)} placeholder="A short storefront description…"/></label></div><section className="admin-form-section"><div className="admin-form-section__head"><div><h3>Shop by Category image</h3><p>Upload one portrait or square JPEG, PNG, or WebP image for this homepage category.</p></div><label className={`admin-upload-button${uploading?' admin-upload-button--busy':''}`}><input type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadImage} disabled={uploading}/>{uploading?'Uploading…':form.image?'Replace image':'Upload image'}</label></div>{form.image?<figure className="admin-category-image-preview"><img src={form.image.url} alt={form.image.alt||form.name}/><figcaption>This image will appear in Shop by Category.</figcaption></figure>:<div className="admin-inline-empty">No category image yet. The storefront fallback will be used.</div>}</section><div className="admin-form-switches"><Toggle checked={form.active} onChange={(value)=>update('active',value)} label="Enabled on storefront"/></div><footer className="admin-form-actions"><button type="button" className="admin-button admin-button--secondary" onClick={close} disabled={saving||uploading}>Cancel</button><button className="admin-button admin-button--primary" disabled={saving||uploading}>{saving?'Saving…':category?'Save changes':'Create category'}</button></footer></form></Modal>;
}

export default function AdminCategories(){
  const {role}=useAuth(),canManage=['superadmin','admin'].includes(role),canArchive=role==='superadmin';
  const [categories,setCategories]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[editing,setEditing]=useState(null),[formOpen,setFormOpen]=useState(false),[archiveTarget,setArchiveTarget]=useState(null),[busyId,setBusyId]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const data=await fetchAdminCategories();setCategories(data.categories||[]);}catch(err){setError(err.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{queueMicrotask(load);},[load]);
  const flash=(message)=>{setNotice(message);setTimeout(()=>setNotice(''),2800);};
  const save=async(payload,id)=>{if(id)await updateAdminCategory(id,payload);else await createAdminCategory(payload);flash(id?'Category updated.':'Category created.');await load();};
  const toggle=async(category,value)=>{setBusyId(category._id);try{await updateAdminCategory(category._id,{active:value});setCategories((current)=>current.map((item)=>item._id===category._id?{...item,active:value}:item));flash(value?'Category enabled.':'Category disabled.');}catch(err){setError(err.message);}finally{setBusyId('');}};
  const archive=async()=>{if(!archiveTarget)return;setBusyId(archiveTarget._id);try{await archiveAdminCategory(archiveTarget._id);setArchiveTarget(null);flash('Category archived.');await load();}catch(err){setError(err.message);}finally{setBusyId('');}};
  return <section className="admin-page admin-collection-page"><header className="admin-page-header"><div><p className="admin-eyebrow">Homepage catalogue</p><h1>Shop by Category</h1><p>Upload artwork and arrange the six categories displayed on the storefront homepage.</p></div>{canManage&&<button className="admin-button admin-button--primary" onClick={()=>{setEditing(null);setFormOpen(true);}}>+ Add category</button>}</header>{notice&&<div className="admin-toast">✓ {notice}</div>}{error&&!loading&&<div className="admin-alert admin-alert--error admin-alert--row"><span>{error}</span><button onClick={load}>Retry</button></div>}{loading?<div className="admin-list-skeleton">{[1,2,3,4].map((item)=><div key={item}/>)}</div>:categories.length===0?<PageState type="empty" title="No categories yet" message="Create your first category to organise the SKYRA catalogue." action={canManage?<button className="admin-button admin-button--primary" onClick={()=>setFormOpen(true)}>Add category</button>:null}/>:<div className="admin-category-grid">{categories.map((category,index)=><article className="admin-category-card" key={category._id}>{category.image?.url&&<img className="admin-category-card__image" src={category.image.url} alt={category.image.alt||category.name}/>}<div className="admin-category-card__order">{String(category.sortOrder??index).padStart(2,'0')}</div><div className="admin-category-card__body"><div className="admin-category-card__head"><span className={`admin-status ${category.active?'admin-status--confirmed':'admin-status--cancelled'}`}>{category.active?'Enabled':'Disabled'}</span><Toggle checked={category.active!==false} disabled={!canManage||busyId===category._id} onChange={(value)=>toggle(category,value)}/></div><h2>{category.name}</h2><code>/{category.slug}</code><p>{category.description||'No description has been added.'}</p></div><footer><span>Display order {category.sortOrder||0}</span><div className="admin-row-actions">{canManage&&<button onClick={()=>{setEditing(category);setFormOpen(true);}}>Edit image</button>}{canArchive&&<button className="admin-text-danger" onClick={()=>setArchiveTarget(category)}>Archive</button>}</div></footer></article>)}</div>}{formOpen&&<CategoryForm key={editing?._id||'new-category'} open category={editing} onClose={()=>setFormOpen(false)} onSave={save}/>}<ConfirmModal open={Boolean(archiveTarget)} onClose={()=>setArchiveTarget(null)} onConfirm={archive} busy={busyId===archiveTarget?._id} title="Archive this category?" message={`${archiveTarget?.name||'This category'} will be removed from storefront navigation. Categories containing products must be emptied first.`}/></section>;
}
